#!/usr/bin/env bash
# the  same as task 0 but -f added to ln to forcefully remove the file if it exists
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
